/**
 * Technical data pulled from LEUCO's German catalog.
 *
 * The US store carries only what fits in a variant's size label; the German
 * parent publishes the full dimensional spec, which machines a tool fits, what
 * it is for, and material-specific processing instructions as PDFs. This
 * renders that, keyed by the variant SKU (which is LEUCO's material number).
 *
 * Dataset is regenerated by the leuco-spec-sync tool:
 *   cd ~/Documents/Claude/leuco-spec-sync && npm run pull
 *   cp data/site-specs.json <this repo>/data/leuco-specs.json
 *
 * About half the catalog has no German record. Every export here returns
 * null/empty for those so the page falls back to exactly what it shows today.
 */

import specs from '@/data/leuco-specs.json';

export interface LeucoSpecEntry {
    sku: string;
    name: string;
    dimensions?: string;
    specs: Array<{ label: string; value: string }>;
    application?: string;
    machines?: string;
    design?: string;
    advantages?: string;
    documents: Array<{ title: string; url: string; kind: string }>;
    sourceUrl?: string;
}

const CATALOG = specs as unknown as Record<string, LeucoSpecEntry>;

export function getLeucoSpec(sku: string | null | undefined): LeucoSpecEntry | null {
    if (!sku) return null;
    return CATALOG[sku.trim()] ?? null;
}

/**
 * Family-level content for a whole product.
 *
 * LEUCO writes application notes, machine fit and documentation per product
 * family, not per size — which is why the metafield sink puts them on the
 * product and only the spec table on the variant. The page has to match that,
 * or the Application and Documentation tabs appear and vanish as the shopper
 * clicks between sizes: a 280 mm blade with no German record would hide the
 * documents that a 308 mm blade in the same family carries.
 *
 * Prefers the selected variant's own entry so its wording stays in step with
 * the spec table, then falls back to any sibling that has the content.
 */
export function getFamilySpec(
    skus: Array<string | null | undefined>,
    preferredSku?: string | null,
): LeucoSpecEntry | null {
    const preferred = getLeucoSpec(preferredSku);
    if (preferred && hasFamilyContent(preferred)) return preferred;

    for (const sku of skus) {
        const entry = getLeucoSpec(sku);
        if (entry && hasFamilyContent(entry)) return entry;
    }
    return preferred;
}

function hasFamilyContent(entry: LeucoSpecEntry): boolean {
    return Boolean(
        entry.application ||
            entry.machines ||
            entry.design ||
            entry.advantages ||
            entry.documents.length,
    );
}

/**
 * Spec rows as schema.org PropertyValue pairs, for the product JSON-LD.
 * Part-number and spec queries are the capture pillar this data exists to
 * serve, so the structured data matters as much as the visible table.
 */
export function leucoSpecJsonLd(
    skus: Array<string | null | undefined>,
): Array<Record<string, string>> {
    for (const sku of skus) {
        const entry = getLeucoSpec(sku);
        if (entry?.specs.length) {
            return entry.specs.map((s) => ({
                '@type': 'PropertyValue',
                name: s.label,
                value: s.value,
            }));
        }
    }
    return [];
}

/** The authoritative spec table, styled to match the page's existing one. */
export function LeucoSpecTable({ entry }: { entry: LeucoSpecEntry }) {
    return (
        <table className="w-full text-sm">
            <tbody>
                {entry.specs.map((spec, i) => (
                    <tr key={spec.label} className={i % 2 === 0 ? 'bg-white' : 'bg-gray-50'}>
                        <td className="px-5 py-3 font-black text-gray-700 w-1/2">{spec.label}</td>
                        <td className="px-5 py-3 text-gray-600">{spec.value}</td>
                    </tr>
                ))}
            </tbody>
        </table>
    );
}

/**
 * Application / Machines / Design / Advantages — prose the US site has no
 * equivalent for anywhere. Sits under the spec table.
 */
export function LeucoApplicationNotes({ entry }: { entry: LeucoSpecEntry }) {
    const blocks: Array<[string, string | undefined]> = [
        ['Application', entry.application],
        ['Machines', entry.machines],
        ['Design', entry.design],
        ['Advantages', entry.advantages],
    ];
    const present = blocks.filter(([, body]) => body);
    if (present.length === 0) return null;

    return (
        <div className="mb-8 grid grid-cols-1 sm:grid-cols-2 gap-6">
            {present.map(([title, body]) => (
                <div key={title}>
                    <h3 className="text-xs font-black text-gray-400 uppercase tracking-widest mb-2">
                        {title}
                    </h3>
                    <ul className="flex flex-col gap-1">
                        {body!.split('\n').filter(Boolean).map((line, i) => (
                            <li key={i} className="text-sm text-gray-600 flex gap-2">
                                <span className="text-leuco-purple mt-[2px]">—</span>
                                <span>{line}</span>
                            </li>
                        ))}
                    </ul>
                </div>
            ))}
        </div>
    );
}

/**
 * PDF documentation. Renders nothing when the tool has none.
 * No heading of its own — it sits inside a tab that already names it.
 */
export function LeucoDocuments({ entry }: { entry: LeucoSpecEntry }) {
    if (entry.documents.length === 0) return null;

    return (
        <div>
            <ul className="flex flex-col gap-2">
                {entry.documents.map((doc) => (
                    <li key={doc.url}>
                        <a
                            href={doc.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="group flex items-start gap-3 text-sm text-gray-700 hover:text-leuco-purple transition-colors"
                        >
                            <svg
                                viewBox="0 0 24 24"
                                fill="none"
                                stroke="currentColor"
                                strokeWidth="2"
                                className="w-4 h-4 mt-[2px] shrink-0 text-gray-400 group-hover:text-leuco-purple transition-colors"
                                aria-hidden="true"
                            >
                                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                                <path d="M14 2v6h6" />
                            </svg>
                            <span className="font-bold underline underline-offset-2 group-hover:no-underline">
                                {doc.title}
                            </span>
                        </a>
                    </li>
                ))}
            </ul>
            <p className="mt-4 text-xs text-gray-400">
                Published by LEUCO. Opens on leuco.com.
            </p>
        </div>
    );
}
